# import numpy

In [2]:
import numpy as np

## difference b/w numpy array and list

In [2]:
python_list=[1,2,3,4,5]
print(python_list)

numpy_array=np.array([1,2,3,4,5])
print(numpy_array)

#you will see numpy array prints output without commas that is because of how it stores numbers in the memory location

[1, 2, 3, 4, 5]
[1 2 3 4 5]


### one dimensional array

In [3]:
#it is simply list of numbers stored in single row
ar_1d=np.array([1,2,3,4,5])
print(ar_1d)

[1 2 3 4 5]


### two dimensional array

In [5]:
#it is like a table with rows and columns
arr_2d=np.array([[1,2,3],[2,1,3],[3,1,2]])
print(arr_2d)

[[1 2 3]
 [2 1 3]
 [3 1 2]]


### how to create array with default values that have to be changed in future

In [12]:
#zeros function
arr=np.zeros(3)
print(arr)

#zeros function for 2d arrays

arr2=np.zeros((3,3))#we enter it in format of tuple
print(arr2)


#ones function
#if we want to put 1 instead of zeros
ones_arr=np.ones(3)
print(ones_arr)

#ones function with 2d array

ones_arr2=np.ones((2,3))
print(ones_arr2)


#how to add number of your choice as default

#use full function

full_arrayy=np.full(3,4)#first argument will be the shape and second will be the number that is to be the default value
print(full_arrayy)


[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[4 4 4]


### creating sequence of number in numpy


In [ ]:
#for this we use arrange function
#syntax - arange(start,stop,step)

arr=np.arange(1,10,2)
print(arr)

#how to create identity matrix
#we use eye function
id_matrix=np.eye(3)
print(id_matrix)


[1 3 5 7 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## how is numpy array stored in memory

#### - Homogeneous storage: All elements must be of the same type (e.g., all integers or all floats).
- Contiguous block of memory: Data is stored in one continuous chunk, like in C arrays.
- Compact representation: No extra metadata per element; just raw numbers stored sequentially.
- Fast access: Because of contiguous memory, NumPy can use vectorized operations (SIMD instructions, optimized C/Fortran code).
- Strides: NumPy uses strides to calculate the position of each element in memory.


## numpy array properties

In [ ]:
# basic properties of numpy array include shape,size,type,etc.

#shape function allows you to know the shape of the array

arr_2d=np.array([[1,2,3],[1,2,3]])
print(arr_2d.shape)

# size function gives you the number of elements present
print(arr_2d.size)

#to check dimension we use ndim functions

print(arr_2d.ndim)

#to check the type of data it stores use dtype

print(arr_2d.dtype)

#to convert data type
print(arr_2d.astype(str))


(2, 3)
6
2
int64
[['1' '2' '3']
 ['1' '2' '3']]
int64


# Mathematical Operations 

In [ ]:
#lets take an array and perform mathematical operations on it

arrr=np.array([1,2,3,4,5])
#lets take look at the aggregate functions 

# sum function
print(np.sum(arrr))

#mean function
print(np.mean(arrr))

#min function
print(np.min(arrr))

#max function

print(np.max(arrr))

#standard deviation
print(np.std(arrr))



15
3.0
1
5
1.4142135623730951


# Indexing and slicing 

#### concepts to follow:
 indexing
 slicing 
 fancy indexing
 boolean masking 

In [8]:
#how to access a specific element from array (indexing)
#index starts from 0 and if you want to start with the last element the index starts with -1
nparr=np.array([10,20,30,40,50])
print(nparr[0])
print(nparr[1])
#what if i enter an index that doesnt exist- throws error

#slicing- to access a certain range
#syntax- array[start:stop:step] we pass index not the values
#the stop index is excluded
#default value of step size is 1
#if we give negative step value the array will be in reversed order

print(nparr[1:5])#gave both start and stop it will run till index 4 as last value is excluded
print(nparr[:5])#only gave end value so it will start from 0 index ie the start
print(nparr[::2])#only gave step value will give every second value
print(nparr[::-1])#this will reverse the array



#fancy indexing - selecting multiple elements at once
print(nparr[[0,2,4]])#this creates an copy of the original data


#boolean masking - filter data according to some conditions
print(nparr[nparr>25])#we could use loops but boolean masking is 10x faster







10
20
[20 30 40 50]
[10 20 30 40 50]
[10 30 50]
[50 40 30 20 10]
[10 30 50]
[30 40 50]


# Reshaping

#### we use reshaping when we want to change dimensions without changing the data

In [13]:
npparr=np.array([10,20,30,40,50,60])
#you can only reshape if dimensions match

reshaped_arr=npparr.reshape(2,3)
print(reshaped_arr)# reshpae doesnt create a copy it shows you a view and affects the original array


#flattening the array - to convert multi dimensional array into one dimensional array
# we can use two functions - ravel , flatten
#ravel affects the original array 
# flatten doesnt affect the original array

d2_arr=np.array([[1,2,3],[3,2,1]])
print(d2_arr.ravel())
print(d2_arr.flatten())



[[10 20 30]
 [40 50 60]]
[1 2 3 3 2 1]
[1 2 3 3 2 1]
