# Modifications in an Arrays

In [1]:
import numpy as np

### How to insert,delete,stack,split,etc in arrays


In [ ]:
#in numpy array the size of the array is fixed so to perform any of the above functions 
# we have to create a new array 

#to insert a new element 
# syntax - np.insert(array,index,value,axis=None) #axis = None will add data into a flattened array
#axis=1 will add column wise
#axis=0 will add row wise


#lets take an sample array we will perform all functions on this array 
arr=np.array([10,20,30,40,50])
new_arr=np.insert(arr,2,100)
print(new_arr)
print(arr)

#how to insert into a 2d array

arr_2d=np.array([[1,2],[1,2]])
neww_arr=np.insert(arr_2d,1,[5,6],axis=0)
print(neww_arr)
print(arr_2d)


[ 10  20 100  30  40  50]
[10 20 30 40 50]
[[1 2]
 [5 6]
 [1 2]]
[[1 2]
 [1 2]]


In [6]:
#insert element at the end -> append function

neww_ar=np.append(arr,[80,90,100])
print(neww_ar)


[ 10  20  30  40  50  80  90 100]


In [7]:
#concatenate two arrays
#syntax=np.concatenate((arr1,arr2),axis=0) axis can be 0,1,None
ar=np.array([1,2,3,4,5])
arrr=np.array([6,7,8,9,10])
combined=np.concatenate((ar,arrr),axis=0)
print(combined)


[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
#remove an element from an array -> delete function
#syntax-np.delete(array,index,axis=None)axis=None -> flattened array

rmarr=np.array([10,20,30,40,50])
print(arr)

n=np.delete(rmarr,0)
print(n)


#for 2-d arrays
x=np.array([[1,2],[3,4],[5,6]])

new_x=np.delete(x,0,axis=0)
print(new_x)

[10 20 30 40 50]
[20 30 40 50]
[[3 4]
 [5 6]]


In [12]:
#stacking and splitting an array

y=np.array([[1,2],[3,4],[5,6]])
z=np.array([[7,8],[9,10],[11,12]])

# for stacking we have two options -> vstack and hstack

print(np.vstack(((y,z))))#stacks vertically

print(np.hstack(((y,z))))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [16]:
#for splitting arrays
'''
we have three methods
1. np.split()
2. np.vsplit()
3. np.hsplit()
'''
a=np.array([1,2,3,4,5,6,7,8,9])
print(np.split(a,3))


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
