#  Broadcasting and Vectorization 

##### Broadcasting in NumPy is the set of rules that allow arrays of different shapes to be used together in arithmetic operations by automatically expanding the smaller array to match the larger one. It makes element‑wise operations efficient without needing explicit loops or reshaping.

##### Vectorization in NumPy means performing operations on entire arrays at once, without writing explicit Python loops. It leverages optimized C/C++ implementations under the hood, making computations faster, cleaner, and more scalable.





In [1]:
import numpy as np

# Rules of broadcasting

### how does numpy handles arrays of different shapes
    1. matching dimensions
    2. expanding single elements
    3. incompatible shapes

In [3]:
#example
arr=np.array([100,200,400])
result=arr*2
print(result)


#for 2-d array
matrix=np.array([[1,2,3],[4,5,6]])  #2x3 matrix
vector=np.array([10,20,30])

result=matrix+vector
print(result)

[200 400 800]
[[11 22 33]
 [14 25 36]]
